services:
  - type: web
    name: order-management-app
    env: node
    plan: free
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NPM_CONFIG_LEGACY_PEER_DEPS
        value: "true"
    healthCheckPath: /
    autoDeploy: true
    buildFilter:
      paths:
        - src/**
        - public/**
        - package.json
        - next.config.js 